### ISSUE TITLE
default branch for stograde repo

### ISSUE THREAD

**Issue by rabstolaf** [stograde/stograde#297]
We've switched our git servers to use main instead of master as the default branch for repos, including student course repos, which is now the new norm elsewhere as well.  

- Is there a way to configure **stograde repo** to indicate the default branch?
- Would you consider changing the "default default branch" to main?

**Comment by hawkrives** [comment]
Absolutely.

**Comment by hawkrives** [comment]
The default branch has been renamed!

`master` is now named `main`. 

If you have a local clone, you can update it by running the following commands.

``` 
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
